name: TruffleHog Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TruffleHog
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g trufflehog
      - name: Run TruffleHog
        run: trufflehog --entropy=False --paths src,test,config --json > trufflehog-report.json
      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: snyk-report.json
